language: julia

julia:
  - 1.3
  - 1.5

os:
  - linux
  - osx
  - freebsd
  - windows

arch:
  - x86
  - x64
  - arm64

notifications:
  email: false
codecov: true

cache:
  directories:
  - $HOME/.julia/artifacts

branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags
